# 修改默认快捷键
# 所有操作均需要先按键Ctrl + j
# 下面bind-key指定的就是各种快捷键. 区分大小写. C-x代表Ctrl + x
set-option -g prefix C-j
# 鼠标控制, 默认关闭
set-window-option -g mouse off
# vi使用习惯
set-window-option -g mode-keys vi
unbind-key C-b
bind-key C-b send-prefix
# 缓冲区调大
set-option -g history-limit 160000

# 取消一些系统内置的快捷键
unbind-key Up
unbind-key Down
unbind-key Left
unbind-key Right
unbind-key M-Up
unbind-key M-Down
unbind-key M-Left
unbind-key M-Right
unbind-key C-Up
unbind-key C-Down
unbind-key C-Left
unbind-key C-Right
unbind-key "\""
unbind-key %
unbind-key &
unbind-key C-l
unbind-key "\$"
unbind-key ,

# 常用快捷键
bind-key v split-window -h # 垂直切分
bind-key s split-window # 水平切分

# 分区切换
bind-key k select-pane -U # 多个pane之间切换时的上下左右
bind-key j select-pane -D
bind-key h select-pane -L
bind-key l select-pane -R

# 分区大小调整
bind-key -r K resize-pane -U 5 # 调整pane大小
bind-key -r J resize-pane -D 5
bind-key -r H resize-pane -L 5
bind-key -r L resize-pane -R 5

# 窗口管理
bind-key w choose-window # 选择窗口
bind-key C-l list-panes # 选择pane
bind-key C-o rotate-window # 旋转pane
bind-key C-k confirm-before -p "kill-window #W? (y/n)" kill-window # 关闭窗口

# 重命名窗口或会话
bind-key R command-prompt -I "#S" "rename-session '%%'" # 重命名会话
bind-key r command-prompt -I "#W" "rename-window '%%'" # 重命名窗口

# 多窗口同步操作
bind-key t setw synchronize-panes on # 打开所有pane之间操作同步
bind-key T setw synchronize-panes off # 关闭所有pane之间的操作同步

# 打开鼠标支持
bind-key m setw -g mouse on
bind-key M setw -g mouse off

# 挂起其他pane
bind-key z resize-pane -Z \; send-keys C-l
